name: Build LieVPN (Windows & iOS)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.4'
          cache-dependency-path: core/go.sum

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: '3.47.1'
          cache: true

      - name: Get Flutter Dependency
        run: |
          flutter --version
          flutter pub get

      - name: Setup & Build Windows
        run: dart setup.dart windows -v

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LieVPN-Windows
          path: ./dist/*
          overwrite: true

  build-ios:
    name: Build iOS IPA
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: '3.47.1'
          cache: true

      - name: Setup CocoaPods
        run: |
          pod --version

      - name: Get Flutter Dependencies
        run: |
          flutter --version
          flutter pub get

      - name: Build iOS Application
        run: |
          flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          mkdir -p dist/Payload
          cp -r build/ios/iphoneos/Runner.app dist/Payload/
          cd dist
          zip -r -q LieVPN-1.0.4-ios.ipa Payload
          cp LieVPN-1.0.4-ios.ipa LieVPN-ios.ipa
          rm -rf Payload
          ls -lh

      - name: Upload iOS IPA Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LieVPN-iOS-IPA
          path: ./dist/*.ipa
          overwrite: true
