name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.4'
          cache-dependency-path: core/go.sum

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: build-ndk
        with:
          ndk-version: r28c
          link-to-sdk: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: '3.47.1'
          cache: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Get Flutter Dependency
        run: |
          flutter --version
          flutter pub get

      - name: Setup & Build Android
        env:
          ANDROID_NDK_HOME: ${{ steps.build-ndk.outputs.ndk-path }}
        run: dart setup.dart android -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LieVPN-Android-APK
          path: ./dist/*
          overwrite: true
